version: "3.8"

services:
  fastapi-server:
    container_name: "fastapi-server"
    image: fastapi-server
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"  # Replace with the port your Python app listens on
    dns: "8.8.8.8"    
    networks:
      internal_network:
        ipv4_address: 192.168.8.5

networks:
  internal_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.8.0/16
          gateway: 192.168.8.1