"""Added new columns

Revision ID: 91c716beca9d
Revises: cba7cb1b8032
Create Date: 2024-06-02 23:47:30.335538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c716beca9d'
down_revision: Union[str, None] = 'cba7cb1b8032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.CHAR(length=255), nullable=False))
    op.add_column('products', sa.Column('category', sa.CHAR(length=255), nullable=False))
    op.add_column('products', sa.Column('price', sa.REAL(), nullable=False))
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'price')
    op.drop_column('products', 'category')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
